version: '3.8'

services:
  # --- 1. Телеграм Бот ---
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telega_bot
    restart: always
    env_file: .env
    networks:
      - app_network
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # --- 2. Парсер (с планировщиком) ---
  data-parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    container_name: telega_parser
    restart: always
    env_file: .env
    networks:
      - app_network
    volumes:
      - ./sessions:/app/sessions
      - ./logs:/app/logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app_network:
    driver: bridge