version: '3.8' # Можно оставить, но Docker его игнорирует
services:
  # --- 1. Телеграм Бот ---
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: telega_bot
    restart: always
    # Передаем файл .env, где указаны внешние POSTGRESQL_HOST и порт
    env_file: .env
    volumes:
      - ./sessions:/app/sessions  # Сохраняем сессии
      - ./logs:/app/logs
    # Порт 8080 - пример, если боту нужен вебхук или health check
    # ports:
    #   - "8080:8080"

  # --- 2. Парсер (с планировщиком) ---
  data-parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    container_name: telega_parser
    restart: always
    # Передаем файл .env, где указаны внешние POSTGRESQL_HOST и порт
    env_file: .env
    volumes:
      - ./sessions:/app/sessions  # Общая папка с сессиями
      - ./logs:/app/logs

# Секция volumes удалена, так как нет локальной базы данных